services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    networks:
      - arcane_net
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - ./projects:/app/data/projects
    environment:
      - ARCANE_USER=arcane
      - ARCANE_PASSWORD=arcane-admin
      - APP_URL=http://localhost:3552
      - PUID=1000
      - PGID=1000
        # openssl rand -base64 32
      - ENCRYPTION_KEY=/unrbo/RsrtmeVA5hSL70V5XQwXB2nkPhWspvAIou9A=
        # openssl rand -hex 32
      - JWT_SECRET=008b2d28c5559d85b2ba731192e6ad7b64964f7799f28889d41fcd9153ee2b05
    restart: unless-stopped

volumes:
  arcane-data:

networks:
  arcane_net:
    external: true


# docker network create arcane_net
