services:
  web-insti:
    build: .
    container_name: web-insti-elena
    ports:
      - "8080:80"
    networks:
      - red_ia
    restart: unless-stopped

networks:
  red_ia:
    external: true


# sudo docker network create red_ia
